---
deployment:
  tasks:
    - export DEPLOYPATH=/home/asdqwe/public_html/
    - mkdir -p $DEPLOYPATH
    
    # Copy all PHP files (main pages + includes)
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp about.php $DEPLOYPATH
    - /bin/cp services.php $DEPLOYPATH
    - /bin/cp contact.php $DEPLOYPATH
    - /bin/cp portfolio.php $DEPLOYPATH
    - /bin/cp header.php $DEPLOYPATH
    - /bin/cp footer.php $DEPLOYPATH
    - /bin/cp navigation.php $DEPLOYPATH
    
    # Copy CSS and JS files
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp script.js $DEPLOYPATH
    
    # Copy .htaccess
    - /bin/cp .htaccess $DEPLOYPATH/.htaccess
    
    # Copy SSL certificate validation file
    - /bin/cp .well-known/pki-validation/EE84DF98F78A881D434B39C8841F506D.txt $DEPLOYPATH/.well-known/pki-validation/
    
    # Set basic permissions
    - /bin/chmod 644 $DEPLOYPATH/*.php
    - /bin/chmod 644 $DEPLOYPATH/*.css
    - /bin/chmod 644 $DEPLOYPATH/*.js
    - /bin/chmod 644 $DEPLOYPATH/.htaccess