---
deployment:
  tasks:
    - export DEPLOYPATH=/home/asdqwe/public_html/
    
    # For lplk.org.pl domain - ensure proper directory structure
    - mkdir -p $DEPLOYPATH
    
    # Alternative paths to try if main path doesn't work
    # - export DEPLOYPATH=/home/asdqwe/public_html/lplk.org.pl/
    # - export DEPLOYPATH=/home/asdqwe/domains/lplk.org.pl/public_html/
    
    # Copy main PHP files
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp about.php $DEPLOYPATH
    - /bin/cp products.php $DEPLOYPATH
    - /bin/cp services.php $DEPLOYPATH
    - /bin/cp contact.php $DEPLOYPATH
    - /bin/cp test-domain.php $DEPLOYPATH
    # Copy .htaccess (universal configuration)
    - /bin/cp .htaccess $DEPLOYPATH/.htaccess
    
    # Copy includes directory
    - /bin/cp -R includes $DEPLOYPATH
    
    # Copy assets directory (CSS, JS, images) - ensure it's copied
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R assets/css $DEPLOYPATH/assets/ || true
    - /bin/cp -R assets/js $DEPLOYPATH/assets/ || true
    
    # Ensure JavaScript file is copied
    - /bin/cp assets/js/script.js $DEPLOYPATH/assets/js/ || true
    
    # Copy SSL certificate validation file
    - /bin/cp -R .well-known $DEPLOYPATH
    
    # Copy any additional files
    - /bin/cp EE84DF98F78A881D434B39C8841F506D.txt $DEPLOYPATH || true
    
    # Set proper permissions (fix 403 errors)
    - /bin/chmod -R 755 $DEPLOYPATH
    - /bin/chmod 644 $DEPLOYPATH/*.php
    - /bin/chmod 644 $DEPLOYPATH/*.txt
    - /bin/chmod 644 $DEPLOYPATH/.htaccess
    - /bin/chmod -R 644 $DEPLOYPATH/assets/
    - /bin/chmod -R 644 $DEPLOYPATH/includes/
    - /bin/chmod -R 644 $DEPLOYPATH/.well-known/
    
    # Ensure directories are executable
    - /bin/chmod 755 $DEPLOYPATH/assets
    - /bin/chmod 755 $DEPLOYPATH/assets/css
    - /bin/chmod 755 $DEPLOYPATH/assets/js
    - /bin/chmod 755 $DEPLOYPATH/includes
    - /bin/chmod 755 $DEPLOYPATH/.well-known
    - /bin/chmod 755 $DEPLOYPATH/.well-known/pki-validation
    
    # Create backup of current deployment
    - /bin/cp -R $DEPLOYPATH $DEPLOYPATH.backup.$(date +%Y%m%d_%H%M%S) || true