---
deployment:
  tasks:
    - export DEPLOYPATH=/home/asdqwe/public_html/
    - mkdir -p $DEPLOYPATH
    
    # Copy main PHP files
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp about.php $DEPLOYPATH
    - /bin/cp services.php $DEPLOYPATH
    - /bin/cp contact.php $DEPLOYPATH
    - /bin/cp portfolio.php $DEPLOYPATH
    
    # Copy .htaccess
    - /bin/cp .htaccess $DEPLOYPATH/.htaccess
    
    # Copy includes files to root (no folders)
    - /bin/cp includes/header.php $DEPLOYPATH/header.php
    - /bin/cp includes/footer.php $DEPLOYPATH/footer.php
    - /bin/cp includes/navigation.php $DEPLOYPATH/navigation.php
    
    # Copy assets files to root (no folders)
    - /bin/cp assets/css/style.css $DEPLOYPATH/style.css
    - /bin/cp assets/js/script.js $DEPLOYPATH/script.js
    
    # Copy SSL certificate validation file only
    - /bin/cp .well-known/pki-validation/EE84DF98F78A881D434B39C8841F506D.txt $DEPLOYPATH/.well-known/pki-validation/
    
    # Set basic permissions
    - /bin/chmod 644 $DEPLOYPATH/*.php
    - /bin/chmod 644 $DEPLOYPATH/.htaccess